- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME')}}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME')}}/.ssh/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/zsh-setup.yml # ok
    - include: tasks/node-setup.yml
    - include: tasks/core-setup.yml # ok
    - include: tasks/git-setup.yml
    - include: tasks/ssh.yml
    - include: tasks/nvim-setup.yml # ok
    - include: tasks/npm-packages.yml # ok
    - include: tasks/productivity-tools.yml
