- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - neovim
    - core
    - all
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - neovim
    - core
- name: Install System Packages 3 (the rest)
  apt: name={{item}}
  with_items:
    - curl
    - htop
    - golang
    - lsof
    - i3
    - ccache
    - ninja-build
    - python3-pip
    - dconf-editor
    - nvidia-settings
    - brave-browser
    - pavucontrol
    - clangd
  tags:
    - core


