- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  apt_repository:
   repo: ppa:kdenlive/kdenlive-stable
   state: present
   update_cache: True
  tags:
    - all
    - productivity

- name: Install packages
  apt: name={{item}}
  with_items:
    - stow
    - tmux
    - wireshark
    - fzf
    - kdenlive
    - gimp
    - xclip
    - screenkey
    - tldr
  tags:
    - all
    - productivity
- name: dotfile install
  ansible.builtin.git:
    repo: 'https://github.com/ThePrimeagen/.dotfiles'
    dest: $HOME/dotfiles
  tags:
    - all
    - dotfiles
- name: stow dotfiles
  shell: cd $HOME/dotfiles && ./ubuntu
  tags:
    - all
    - dotfiles
